### ISSUE TITLE
activity.list() returns only the last 20 activities

### ISSUE THREAD

**Issue by BS-13** [jsmits/zwift-client#18]
* Zwift Mobile API client version: 0.10
* Python version: 3.6
* Operating System: MAC OS

### Description

Feature request/enhancement: Trying to return all of the activities between a specified start and end date OR retrieve the last “n” activities. The function activity.list() returns only the last 20 activities. 

Would want something like 

activity.listByDate(startDate, endDate) 

OR

activity.list(numberOfActivities) # max is 365, at least a years worth

### What I Did

>>> activity = client.get_activity(player_id)
>>> activities = activity.list()  # your activities
>>> print ( activities )

**Comment by jsmits** [comment]
Yes, good idea.

Just curious: for what do you (plan to) use zwift-client?

**Comment by BS-13** [comment]
I would like to be able to calculate and create a dashboard of Zwift usage by year/month - total Km’s ridden in a month, number of rides that month, average speed for the month, etc.  Sort of like the dashboards you get in Strava Premium :)

Personal usage, but will share :)

Thanks, Bert

On Feb 28, 2018, at 4:45 AM, Sander Smits <notifications@github.com> wrote:

Yes, good idea.

Just curious: for what do you (plan to) use zwift-client?

**Comment by jsmits** [comment]
Sounds good!

Was just trying some code for your idea. It seems like you can get what you want already (sort of):

For example:
```
activities = activity.request.json('/api/profiles/{}/activities/?start={}&limit={}'.format(activity.player_id, 10,40))
```
This will give you activity -10 to -50, starting on the 10th from now in the past and limiting the response to a total of 40. I don't know the upper-bound of limit, since I just started riding on Zwift and only have 23 activities :) But you can try yourself, of course, and play with the start and limit values. Not sure if I can search by date (the Zwift API is not public), but my suggestion might be enough for your use-case, I guess. You can always get the dates from the activities in the response.

I'll update the code soonish and will make a release. I think I'll add an optional start and limit argument to the list() method, with defaults of 0 and 20.

**Comment by BS-13** [comment]
Sounds fantastic - thank you. I have hundreds of rides so will be able to test limits :)

Bert

On Feb 28, 2018, at 2:17 PM, Sander Smits <notifications@github.com> wrote:

Sounds good!

Was just trying some code for your idea. It seems like you can get what you want already (sort of):

For example:

activities = activity.request.json('/api/profiles/{}/activities/?start={}&limit={}'.format(activity.player_id, 10,40))
This will give you activity -10 to -50, starting on the 10th from now in the past and limiting the response to a total of 40. I don't know the upper-bound of limit, since I just started riding on Zwift and only have 23 activities :) But you can try yourself, of course, and play with the start and limit values. Not sure if I can search by date (the Zwift API is not public), but my suggestion might be enough for your use-case, I guess. You can always get the dates from the activities in the response.

I'll update the code soonish and will make a release. I think I'll add an optional start and limit argument to the list() method, with defaults of 0 and 20.

**Comment by jsmits** [comment]
#19
